"""empty message

Revision ID: 029fd33e94e8
Revises: 5e193ae938c6
Create Date: 2024-10-04 20:33:20.512448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029fd33e94e8'
down_revision = '5e193ae938c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('start_work', sa.Time(), nullable=False),
    sa.Column('end_work', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
