"""empty message

Revision ID: 5e193ae938c6
Revises: 016e99cd8278
Create Date: 2024-10-04 16:01:53.359848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e193ae938c6'
down_revision = '016e99cd8278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('species', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=128), nullable=True),
    sa.Column('birth', sa.DateTime(), nullable=True),
    sa.Column('age', sa.String(length=128), nullable=True),
    sa.Column('habitat', sa.String(length=128), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal')
    # ### end Alembic commands ###
